apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesFleetManager
metadata:
  annotations:
    meta.upbound.io/example-id: containerservice/v1beta1/kubernetesfleetmanager
  labels:
    testing.upbound.io/example-name: example
  name: usprodfleet01
spec:
  forProvider:
    hubProfile:
      - dnsPrefix: dsolusprodfleet01
    location: West US 2
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: infracluster01_group