apiVersion: azure.upbound.io/v1beta1
kind: ResourceGroup
metadata:
  name: prod-clu-grp02
  metadata:
  labels:
    testing.upbound.io/example-name: prod-clu-grp02
spec:
  forProvider:
    location: "East US 2"
  providerConfigRef:
    name: default
---
apiVersion: containerservice.azure.upbound.io/v1beta1
kind: KubernetesCluster
metadata:
  labels:
    testing.upbound.io/example-name: akswkldclu002
  name: akswkldclu002
spec:
  forProvider:
    defaultNodePool:
      - name: default
        nodeCount: 1
        vmSize: Standard_D2_v2
    dnsPrefix: exampleaks2
    identity:
      - type: SystemAssigned
    location: East US 2
    resourceGroupNameSelector:
      matchLabels:
        testing.upbound.io/example-name: prod-clu-grp02
    tags:
      Environment: Production
      Location: East US 2